### ISSUE TITLE
Set browserslist correctly

### ISSUE THREAD

**Issue by equinusocio** [sdras/cssgridgenerator#13]
A correct browserslist must be defined in order to let PostCSS (already running with Vue CLI) prefix the code. I have a PR ready, i can suggest browsers version where the grid module is natively supported:

```js
[
  "last 2 Chrome versions",
  "last 2 Firefox versions",
  "last 2 Safari versions",
  "last 2 Edge versions"
]
```

Then remove prefixed code around the repo.

**Comment by sdras** [comment]
Sure, sounds good to me. Please don't remove the prefixes from the gradients, I don't mind them going back further.

**Comment by equinusocio** [comment]
If you set autoprefixer it will add them if required based on the above browsers compatibility list. Why keeping them?

**Comment by sdras** [comment]
Because the gradient prefixes goes back farther than the browserlist you compiled, and I want to keep that.
