### ISSUE TITLE
Allow "auto" values for rows/columns

### ISSUE THREAD

**Issue by oliverjam** [sdras/cssgridgenerator#18]
It would be nice to support `auto`, as well as `max-content` and `min-content` for row and column sizes.

I imagine adding tests for them here would work:
https://github.com/sdras/cssgridgenerator/blob/54e99705166af5a94f79630561eadde01dbd8666/src/components/AppGrid.vue#L89-L96

But I'm not sure how to visualise that on the grid (since the rows/columns have no content to size by). Maybe just default to a ~`2rem` height/width? We can probably assume the user knows what they're doing if they've typed `min-content` in.

I've never written any Vue before but happy to learn to try and PR if you think this would be worthwhile.

**Comment by sdras** [comment]
Sure, I'd take a PR for this :) I was going to offer to just do it, but if you'd like to take a stab at it to learn, that's great!

**Comment by sdras** [comment]
Hey there, still working on this? If not, I can add it myself. Thanks!

**Comment by oliverjam** [comment]
Hey, sorry but to be honest I completely forgot about this! I haven't even started so if you want to add it yourself please go ahead :)

**Comment by sdras** [comment]
Fixed!
