### ISSUE TITLE
rows appear out of main container

### ISSUE THREAD

**Issue by Sawalhah** [sdras/cssgridgenerator#22]
When add rows with total height in pixels more than "gridcontainer" height it appears out of the box.

![image](https://user-images.githubusercontent.com/10211157/58514050-8d349380-81a9-11e9-83f1-a427ab585d03.png)

**Comment by sdras** [comment]
Yeah, but that's literally what the grid will do. I'm not sure I want to guard against the actual behavior, it's important that people see what's really happening to their grids.
