### ISSUE TITLE
Issues when div goes over 20

### ISSUE THREAD

**Issue by alexbowers** [sdras/cssgridgenerator#23]
![image](https://user-images.githubusercontent.com/842974/58516738-f19f2500-81a0-11e9-8b0a-1d298b629084.png)

There seems to be a problem with the labelling over `div20`

**Comment by sdras** [comment]
I'm gonna go ahead and close this out because if you're overlaying divs this much you should just write the code by hand at that point, and apply multiple classes to the same value. This tool isn't really for this use case.
