### ISSUE TITLE
make it possible to undo/unselect divs?

### ISSUE THREAD

**Issue by sw-yx** [sdras/cssgridgenerator#4]
accidental clicks can cause creation of extra divs we didnt mean to make. 

the simple form of this is a "undo" mechanism. probably a vuex thing? idk

the bigger form of this is a click/touch mechanism or logic to know we want to delete stuff

the "galaxy brain" form of this is direct manipulation of the generated code to delete/edit stuff directly, and see the result visualized. altho arguably you could already do that in browser css tools 🤷🏼‍♂️

**Comment by sdras** [comment]
Yeah it wouldn't be too hard to implement :) I'll definitely work on this for next release. Open to PRs too.

**Comment by sjconnor** [comment]
I just put in a PR that does this with shift-click. 

https://github.com/sdras/cssgridgenerator/pull/20

**Comment by ayox** [comment]
I submitted a PR for undo/redo actions #30

**Comment by sdras** [comment]
This is fixed :)
