### ISSUE TITLE
HTML code?

### ISSUE THREAD

**Issue by diomed** [sdras/cssgridgenerator#41]
Why isn't there available option to get HTML code as well, with CSS one?

**Comment by michaelpumo** [comment]
I guess because it's simple enough? e.g.

```
<div class="parent">
  <div class="div1"></div>
  <div class="div2"></div>
  <div class="div3"></div>
</div>
```

**Comment by sdras** [comment]
Yeah, the HTML is pretty straightforward for this. I'm going to close this out but if many other people need it, I'd be open to reopening :)
