### ISSUE TITLE
divs overlaying each other

### ISSUE THREAD

**Issue by diomed** [sdras/cssgridgenerator#42]
why is it allowed for divs to overlay one over another?
this must be some kind of bug. 
it's absurd that one can layer divs on top of each other.

**Comment by SeasonLeee** [comment]
I think we can consider this case in the scenario of parent div containing child div.

**Comment by sdras** [comment]
It's allowed because that's the behavior of grid. This isn't an issue with this project, if you'd like to learn more about CSS Grid, please check out the learning resources linked up in the explanation section.

**Comment by diomed** [comment]
@sdras you'll have to have something like save
like it's done here:
https://grid.layoutit.com/

or simply ability to create layers, and not just like that. 

the way it currently is it's unusable.

**Comment by sdras** [comment]
Please consider the way you're speaking. It's ok to request a feature, but demanding things and calling the tool broadly unusable when you don't speak to others is not welcome here.
