### ISSUE TITLE
Preview of selected area while dragging

### ISSUE THREAD

**Issue by alanlal** [sdras/cssgridgenerator#59]
Hi, 

I was thinking of a feature where you could see the area you're selecting while dragging the mouse across. Currently, the selected area gets visible only when you release the mouse button.

Thoughts ?? :thinking: :smile:

**Comment by sdras** [comment]
Someone put in a PR for this but it felt kind of slow/clunky to me. I wouldn't be adverse to another implementation, but I think for now, keeping the tool a bit more simple is where I'm at with it. If I get many more people asking for this, I'll reconsider. Thanks!
