### ISSUE TITLE
Stacking lots of divs makes text hard to read

### ISSUE THREAD

**Issue by Skraelingjar** [sdras/cssgridgenerator#6]
![Annotation 2019-05-28 083453](https://user-images.githubusercontent.com/6783448/58491458-d7733180-8123-11e9-98df-a507d451ec2a.png)

I don't know why I just kept clicking but it doesn't really get weird until 21. When the columns, rows, and gaps are maxed out it is more apparent. I was able to reproduce this on Chrome, Edge, and Firefox. 

Thank you for making this, it's super cool!

**Comment by sdras** [comment]
I mean, honestly if you're going to be stacking a lot of divs in the same spot, you should probably just write that code by hand, because you can apply multiple classes to the same nested code. This generator shouldn't be used in the place of thinking critically, IMO.
