### ISSUE TITLE
If fr value is same for grid-template-columns & grid-template-rows then why not use repeat!

### ISSUE THREAD

**Issue by IamManchanda** [sdras/cssgridgenerator#64]
Hey Mam,

If in case the `fr` value is same in grid-template-columns & grid-template-rows ... shouldn't we use

```css
grid-template-columns: repeat(10, 1fr); 
grid-template-rows: repeat(10, 1fr);
```

<img width="1470" alt="Screenshot 2019-07-14 at 7 39 35 PM" src="https://user-images.githubusercontent.com/4970624/61184793-54744f00-a66f-11e9-8ee2-3de6feecf441.png">

**Comment by pnevares** [comment]
Hi @IamManchanda, somebody has a pull request for this feature. Please watch #50 for updates!

**Comment by sdras** [comment]
fixed!
