### ISSUE TITLE
"Reset Grid" does not work

### ISSUE THREAD

**Issue by ManojAMK** [sdras/cssgridgenerator#65]
Hello there,

First of all thanks for this very good app which gave me a basic understanding of CSS Grids but I think "Reset Grid" feature does not work on Chrome and Firefox or is it just me? 

**Video:** 

https://www.loom.com/share/1486c9a3c5c64538b232af74cfebec87

**Comment by techytuppers** [comment]
Hey @ManojAMK - The columns/rows/gaps sets your "blueprint" for the grid that you then go on to draw :) screen video here: https://embed.vidyard.com/share/vU4DGEwYiBQvjibmMw1RnX?

**Comment by ManojAMK** [comment]
Never noticed that. Thanks. Can you please include that Screencast in the official website for the newcomers? Most probably they would miss it.
