### ISSUE TITLE
Should Reset Grid button reset row/column/gaps to original values.

### ISSUE THREAD

**Issue by SandipNirmal** [sdras/cssgridgenerator#70]
The `Reset Grid` button is somewhat confusing. Earlier I thought it resets the row/column/gap values but it just resets selections. @sdras Should it clear everything? I am happy to add PR.

**Comment by sdras** [comment]
No, that's not the functionality people requested and I think it would be quite jarring. I also don't want to add too many features- it doesn't seem like it but I've worked really hard to keep it as simple and usable without too much mental overhead as possible. Thanks for the suggestion though!
